# ===== Application =====
spring.application.name=taskflow-api

# ===== Serveur =====
server.port=8080

# ===== Base de donnees H2 (en memoire) =====
spring.datasource.url=jdbc:h2:mem:taskflowdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===== Threads virtuels (Java 25 - Spring Boot 4) =====
spring.threads.virtual.enabled=true

# ===== JWT (expiration 24h) =====
app.jwt.secret=Y2hhbmdlLW1lLXRhc2tmbG93LXNlY3JldC1rZXktMjU2LWJpdHMtbWluaW11bS1sZW5ndGgtcmVxdWlyZWQ=
app.jwt.expiration-ms=86400000

# ===== Springdoc / Swagger =====
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ===== Logging =====
logging.level.com.taskflow=DEBUG
logging.level.org.hibernate.SQL=DEBUG

